In [1]:
import os
import sys
sys.path.append("../../")  # Adds higher directory to python modules path.
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1'


from utils import common_modifiers
import numpy as np
from core.ODEDataset import ODEDataset

# Merge the datasets:
- Kenya
- Zambia
- ESMAP
- Ethiopia
- Liberia

In [2]:
Kenya = ODEDataset("Kenya").from_csv("../../playground/data/ESMAP/kenya/kenya.csv", index_col=0)

Kenya = Kenya.apply(common_modifiers.add_const_driver("Tariff_payment_frequency", np.nan))
Zambia = ODEDataset("Zambia").from_csv("../../playground/data/ESMAP/zambia/Zambia.csv", index_col=0).apply(
    common_modifiers.rename({"HouseholdID": "ID"}))

Nigeria = ODEDataset("Nigeria").from_csv("../../playground/data/ESMAP/nigeria/Nigeria.csv", index_col=0).apply(
    common_modifiers.rename({"HH_ID": "ID"}))

Ethiopia = ODEDataset("Ethiopia").from_csv("../../playground/data/ESMAP/Ethiopia_L/csv_data/Ethiopia.csv", index_col=0)
Liberia = ODEDataset("Liberia").from_csv("../../playground/data/ESMAP/Liberia_L/Liberia.csv", index_col=0)


Kenya = Kenya.apply(common_modifiers.add_const_driver("source","kenya" ))

Zambia = Zambia.apply(common_modifiers.add_const_driver("source","zambia" ))
Nigeria = Nigeria.apply(common_modifiers.add_const_driver("source","nigeria" ))
Ethiopia = Ethiopia.apply(common_modifiers.add_const_driver("source","ethiopia" ))
Liberia = Liberia.apply(common_modifiers.add_const_driver("source","liberia" ))

In [3]:
ESMAP = Kenya.concat(Zambia).concat(Nigeria)
ESMAP = ESMAP.concat(Ethiopia).concat(Liberia)
# %% Save the merged dataset
filename = "../../playground/data/ESMAP/ESMAP_with_source.csv"

ESMAP.to_csv(filename)

In [4]:
ESMAP.preview()

,ID,Years_of_HHH_in_community,Dwelling_quality_index,Hours_available_electricity,Measurement_age,Monthly_expenditure,Number_of_rooms,Climate_zone_lev_1,Climate_zone_lev_2,Age_HHH,...,Clean_fuel,Tariff_payment_frequency,Presence_refrigerator/freezer,Presence_iron,Presence_fan,Presence_DVD_player,Presence_radio/stereo,Presence_phone_charger,Presence_TV,source
0,1001_3,NaN,0.0,NaN,NaN,63600.0,3.0,3.0,NaN,NaN,...,No,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,kenya
1,1001_3,NaN,0.0,NaN,NaN,63600.0,3.0,3.0,NaN,NaN,...,No,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,kenya
2,1026_3,20.0,0.0,NaN,NaN,65400.0,3.0,3.0,3.0,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kenya
3,1026_3,20.0,0.0,NaN,NaN,65400.0,3.0,3.0,3.0,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kenya
4,1027_2,15.0,0.0,NaN,NaN,NaN,2.0,3.0,3.0,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kenya

In [ ]:
import pandas as pd

df = pd.read_csv("../../playground/data/ESMAP/ESMAP.csv")

df.columns

Index(['Unnamed: 0', 'ID', 'Years_of_HHH_in_community',
       'Dwelling_quality_index', 'Hours_available_electricity',
       'Measurement_age', 'Monthly_expenditure', 'Number_of_rooms',
       'Climate_zone_lev_1', 'Climate_zone_lev_2', 'Age_HHH',
       'HH_with_home_business', 'Education_level_HHH', 'Socio_status_HHH',
       'Number_adults', 'Ownership_motorized_vehicle',
       'Ownership_small_livestock', 'Ownership_large_livestock', 'Clean_fuel',
       'Tariff_payment_frequency', 'Presence_refrigerator/freezer',
       'Presence_iron', 'Presence_fan', 'Presence_DVD_player',
       'Presence_radio/stereo', 'Presence_phone_charger', 'Presence_TV'],
      dtype='object')

In [6]:
df

,Unnamed: 0,ID,Years_of_HHH_in_community,Dwelling_quality_index,Hours_available_electricity,Measurement_age,Monthly_expenditure,Number_of_rooms,Climate_zone_lev_1,Climate_zone_lev_2,...,Ownership_large_livestock,Clean_fuel,Tariff_payment_frequency,Presence_refrigerator/freezer,Presence_iron,Presence_fan,Presence_DVD_player,Presence_radio/stereo,Presence_phone_charger,Presence_TV
0,0,1001_3,NaN,0.0,NaN,NaN,63600.000000,3.0,3.00000,NaN,...,No,No,NaN,0.0,0.0,0.0,0.0,0.0,1,0
1,1,1001_3,NaN,0.0,NaN,NaN,63600.000000,3.0,3.00000,NaN,...,No,No,NaN,0.0,0.0,0.0,0.0,0.0,1,0
2,2,1026_3,20.0,0.0,NaN,NaN,65400.000000,3.0,3.00000,3.0,...,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,0,0
3,3,1026_3,20.0,0.0,NaN,NaN,65400.000000,3.0,3.00000,3.0,...,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,0,0
4,4,1027_2,15.0,0.0,NaN,NaN,NaN,2.0,3.00000,3.0,...,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9410,167,uuid:f9abe4c3-04f3-45a5-ae24-9f08238ad2d9,NaN,4.0,NaN,NaN,62641.666667,5.0,13.76250,NaN,...,NaN,No,NaN,0.0,0.0,0.0,0.0,1.0,0,0
9411,168,uuid:fa2570a6-7ea9-4943-a337-7307d05b8224,NaN,5.0,NaN,1.0,745571.666667,5.0,11.73975,NaN,...,NaN,No,NaN,1.0,1.0,1.0,1.0,1.0,1,1
9412,169,uuid:faa1834a-2214-4710-bb91-e1cc8c0c5f8b,NaN,7.0,NaN,4.0,311716.666667,4.0,11.73975,NaN,...,NaN,No,NaN,1.0,0.0,1.0,0.0,1.0,0,1
9413,170,uuid:fd12ddab-cc66-482f-98fb-9a941e11ec8e,NaN,4.8,NaN,NaN,30719.333333,4.0,18.89050,NaN,...,NaN,No,NaN,0.0,0.0,0.0,0.0,1.0,0,0
9414,171,uuid:ff91ca41-4e14-4c4c-988d-3befbe9c37b1,NaN,3.8,NaN,1.0,59434.666667,7.0,16.40725,NaN,...,NaN,No,NaN,0.0,0.0,1.0,0.0,1.0,0,0

In [7]:
Ethiopia.value_counts("Ownership_motorized_vehicle")

Ownership_motorized_vehicle
1.0    149
0.0     75
Name: count, dtype: int64